#!/usr/bin/env node

/**
 * Schema Merger Script
 * 
 * This script merges all .prisma files from the schemas/ directory
 * into a single schema.prisma file in the correct order.
 * 
 * Order matters:
 * 1. base.prisma - generator and datasource
 * 2. user.prisma - User and Profile models
 * 3. rbac.prisma - Role, Permission models
 * 4. session.prisma - Session and token models
 * 5. audit.prisma - Audit log model
 */

const fs = require('fs');
const path = require('path');

const SCHEMAS_DIR = path.join(__dirname, 'schemas');
const OUTPUT_FILE = path.join(__dirname, 'schema.prisma');

// Define the order of schema files
const SCHEMA_ORDER = [
  'base.prisma',
  'user.prisma',
  'rbac.prisma',
  'session.prisma',
  'audit.prisma',
];

function mergeSchemas() {
  console.log('🔄 Merging Prisma schema files...');
  
  let mergedContent = '';
  let hasErrors = false;

  // Add header comment
  mergedContent += `// This is your Prisma schema file,\n`;
  mergedContent += `// learn more about it in the docs: https://pris.ly/d/prisma-schema\n`;
  mergedContent += `//\n`;
  mergedContent += `// ⚠️  WARNING: This file is auto-generated!\n`;
  mergedContent += `// Do not edit this file directly. Edit files in prisma/schemas/ instead.\n`;
  mergedContent += `// Run 'pnpm db:merge' to regenerate this file.\n\n`;

  // Merge files in order
  for (const filename of SCHEMA_ORDER) {
    const filePath = path.join(SCHEMAS_DIR, filename);
    
    if (!fs.existsSync(filePath)) {
      console.error(`❌ Error: File not found: ${filePath}`);
      hasErrors = true;
      continue;
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    
    // Add separator comment
    mergedContent += `\n// ============================================================================\n`;
    mergedContent += `// ${filename.toUpperCase().replace('.PRISMA', '')}\n`;
    mergedContent += `// ============================================================================\n\n`;
    
    // Add file content
    mergedContent += content;
    
    // Add newline at the end if not present
    if (!content.endsWith('\n')) {
      mergedContent += '\n';
    }
    
    console.log(`✅ Merged: ${filename}`);
  }

  // Check for any additional .prisma files not in the order list
  const allFiles = fs.readdirSync(SCHEMAS_DIR)
    .filter(file => file.endsWith('.prisma'))
    .filter(file => !SCHEMA_ORDER.includes(file));

  if (allFiles.length > 0) {
    console.warn(`⚠️  Warning: Found additional schema files not in merge order: ${allFiles.join(', ')}`);
    console.warn(`   Add them to SCHEMA_ORDER in merge-schemas.js to include them.`);
  }

  // Write merged content to schema.prisma
  try {
    fs.writeFileSync(OUTPUT_FILE, mergedContent, 'utf-8');
    console.log(`\n✅ Successfully merged schemas into: ${OUTPUT_FILE}`);
    
    if (hasErrors) {
      console.error('\n⚠️  Some errors occurred during merge. Please check the output above.');
      process.exit(1);
    }
  } catch (error) {
    console.error(`❌ Error writing merged schema: ${error.message}`);
    process.exit(1);
  }
}

// Run the merge
mergeSchemas();

